name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm packages
        run: |
          npm install
          npm ci
        working-directory: ./build # replace with the folder that contains package.json

      - name: Validate ADF resources
        run: |
          npm run build validate "${{ github.workspace }}${{ vars.ADF_ROOT_FOLDER }}" ${{ secrets.ADF_RESOURCE_ID }}
        working-directory: ./build # replace as above

      - name: Validate and generate ARM template
        run: |
          npm run build export "${{ github.workspace }}${{ vars.ADF_ROOT_FOLDER }}" ${{ secrets.ADF_RESOURCE_ID }} "ArmTemplate"
        # For preview mode, replace the above line with your preview command (ensure package.json contains it)
        working-directory: ./build

      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmTemplates
          path: ./build/ArmTemplate # replace with actual path where the export writes templates
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download ARM template artifact
        uses: actions/download-artifact@v4
        with:
          name: ArmTemplates
          path: ./build/ArmTemplate

      # TODO: Add PrePostDeployment script steps here if needed

      - name: Deploy ARM template to Resource Group
        uses: azure/arm-deploy@v2
        with:
          resource-group-name: ${{ vars.ADF_RESOURCE_GROUP }}
          template: ./build/ArmTemplate/ARMTemplateForFactory.json
          parameters: ./build/ArmTemplate/ARMTemplateParametersForFactory.json factoryName="${{ vars.ADF_NAME }}" AzureDataLakeStorage_properties_typeProperties_url="https://stasanprd.dfs.core.windows.net/" AzureSqlDatabase_properties_typeProperties_server="asa-nprd-sql.database.windows.net" AzureSqlDatabase_properties_typeProperties_database="AdventureWorksDB"
          deploymentMode: Incremental
        # additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
