name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm packages
        run: |
          npm install
          npm ci
        working-directory: ./build # replace with the folder that contains package.json

      - name: Validate ADF resources
        run: |
          npm run build validate "${{ github.workspace }}${{ vars.ADF_ROOT_FOLDER }}" ${{ secrets.ADF_RESOURCE_ID }}
        working-directory: ./build # replace as above

      - name: Validate and generate ARM template
        run: |
          npm run build export "${{ github.workspace }}${{ vars.ADF_ROOT_FOLDER }}" ${{ secrets.ADF_RESOURCE_ID }} "ArmTemplate"
        # For preview mode, replace the above line with your preview command (ensure package.json contains it)
        working-directory: ./build

      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmTemplates
          path: ./build/ArmTemplate # replace with actual path where the export writes templates
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download ARM template artifact
        uses: actions/download-artifact@v4
        with:
          name: ArmTemplates
          path: ./build/ArmTemplate

      - name: Upload linked templates to Blob Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            
            ls -la ./build/ArmTemplate/linkedTemplates

            az storage account create --name ${{ vars.ADF_STORAGE_ACCOUNT }} --resource-group ${{ vars.ADF_RESOURCE_GROUP }} --location ${{ vars.ADF_LOCATION }} --sku Standard_LRS --kind StorageV2 --access-tier Hot
            az storage container create --name linkedtemplates --account-name ${{ vars.ADF_STORAGE_ACCOUNT }} --public-access off --auth-mode login
            az storage blob upload-batch --account-name ${{ vars.ADF_STORAGE_ACCOUNT }} --source ./build/ArmTemplate/linkedTemplates --destination linkedtemplates --pattern "*.json" --overwrite --auth-mode login

            SASToken=$(az storage container generate-sas --name linkedtemplates --account-name ${{ vars.ADF_STORAGE_ACCOUNT }} --permissions rwdl --expiry $(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ') --https-only --output tsv)
            echo "SASToken: $SASToken"
            echo "AZURE_STORAGE_CONTAINER_URI=https://${{ vars.ADF_STORAGE_ACCOUNT }}.blob.core.windows.net/linkedtemplates" >> "$GITHUB_ENV"
            echo "AZURE_STORAGE_SAS_TOKEN=$SASToken" >> "$GITHUB_ENV"

          
      # TODO: Add PrePostDeployment script steps here if needed

      # - name: Deploy ARM template to Resource Group
      #   uses: azure/arm-deploy@v2
      #   with:
      #     resourceGroupName: ${{ vars.ADF_RESOURCE_GROUP }}
      #     template: ./build/ArmTemplate/ARMTemplateForFactory.json
      #     parameters: ./build/ArmTemplate/ARMTemplateParametersForFactory.json factoryName="${{ vars.ADF_NAME }}" AzureDataLakeStorage_properties_typeProperties_url="https://stasanprd.dfs.core.windows.net/" AzureSqlDatabase_properties_typeProperties_server="asa-nprd-sql.database.windows.net" AzureSqlDatabase_properties_typeProperties_database="AdventureWorksDB"
      #     deploymentMode: Incremental
      #   # additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"


      - name: Deploy ARM template (Linked) to Resource Group
        uses: azure/arm-deploy@v2
        with:
          deploymentName: "adf-cicd-deployment-${{ github.run_id }}"
          resourceGroupName: ${{ vars.ADF_RESOURCE_GROUP }}
          template: ./build/ArmTemplate/linkedTemplates/ArmTemplate_master.json
          parameters: ./build/ArmTemplate/linkedTemplates/ArmTemplateParameters_master.json factoryName="${{ vars.ADF_NAME }}" AzureDataLakeStorage_properties_typeProperties_url="https://stasanprd.dfs.core.windows.net/" AzureSqlDatabase_properties_typeProperties_server="asa-nprd-sql.database.windows.net" AzureSqlDatabase_properties_typeProperties_database="AdventureWorksDB" containerUri="${{ env.AZURE_STORAGE_CONTAINER_URI }}" containerSasToken="${{ env.AZURE_STORAGE_SAS_TOKEN }}"
          deploymentMode: Incremental
        # additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
